### ISSUE TITLE
Lock expiration

### ISSUE THREAD

**Issue by thlawiczka** [kongluoxing/celerybeatredis#11]
After a fatal death of the beat process, lock "**celery:beat:task_lock**" will block forever, every new process, resulting: 

> "another beat is running, disable this node util it is shutdown"

This issue requires a manual action (DEL "celery:beat:task_lock").

In my opinion, the lock should be set with a TTL (like 2*60s), and is should be upgraded for another TTL periodically (like every 60s), while process is alive. In case of an unexpected termination there is a chance for another beat to take a baton, after a while.

Regard

**Comment by kongluoxing** [comment]
Thanks, merged
