### ISSUE TITLE
Redis keys getting created again and again

### ISSUE THREAD

**Issue by sarthakdev90** [kongluoxing/celerybeatredis#8]
So I have all my periodic tasks under the prefix `periodic:`. When I delete the keys for a subset of them, the keys seem to get created back. As a result, I'm not able to stop `celerybeat` from scheduling these tasks.

**Comment by kongluoxing** [comment]
Do you put tasks in celeryconfig?

**Comment by sarthakdev90** [comment]
No, I have stored these tasks in `redis`.
