### ISSUE TITLE
version bump to 0.1.4

### ISSUE THREAD

**Issue by flokli** [kongluoxing/celerybeatredis#9]
Hey,

could you please release a new version of this module?

I'd like to use it with python3. Unfortunately, the merge pulling in python3 support occured after the release of 0.1.3, so currently, only git master works in python3.

Thanks!

**Comment by Adaptification** [comment]
+1

**Comment by kongluoxing** [comment]
I don't have much time now, but I'm plan to check and solve all the issue at this weekend, you can check this issue next week :)

**Comment by kongluoxing** [comment]
Sorry for the delay, Update to 0.1.5 now!
